Name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Dumper Project
      run: msbuild Dumper/Dumper.vcxproj /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=0

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Dumper-7_x64-Release
        path: |
          x64/Release/Dumper*.dll
          x64/Release/Dumper*.pdb
          
